# Generated by Django 3.2.5 on 2021-07-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_csv_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='position',
            new_name='positions',
        ),
    ]
